version: 2.1
executors:
  my_executor:
    docker:
      - image: cimg/node:16.15

deploy-to-aws: &deploy-to-aws
  executor: my_executor
  steps:
    - checkout
    - add_ssh_keys:
        fingerprints:
          - "83:f4:92:e0:4d:ce:0a:d9:62:0e:99:79:c0:37:9a:0e"
  #  - run: Tagging
  #      name: Release this version
  #      command: ./publish.sh

workflows:
  version: 2
  deploy-to-aws:
    jobs:
      - deploy-to-aws-sandbox:
          context: sandbox-context
          filters:
            branches:
              only:
                - sandbox
      - deploy-to-aws-prod:
          context: production-context
          filters:
            branches:
              only:
                - master

jobs:
  deploy-to-aws-sandbox:
    <<: *deploy-to-aws

  deploy-to-aws-prod:
    <<: *deploy-to-aws

  deploy-to-aws-development:
    <<: *deploy-to-aws


























